# Manipulação de Strings com Python

> Uma variavel primaria de texto é chamada de char ou caracter possibilitando o armazenamento de 8 bits de memória. Quando necessitamos de um conjunto de caracteres utilizamos um objeto, ou variaveis compostas no caso da maioria das linguagens chamadas de string. Vamos ver como se aplica

In [36]:
frase = "Boa tarde a todos"
print(frase) 
saudacao = frase[0:9]
print(saudacao)

Boa tarde a todos
Boa tarde


In [37]:
print(type(frase))
print(type(saudacao))

<class 'str'>
<class 'str'>


In [38]:
print(frase.count(' '))
print(saudacao.count(' '))

3
1


In [39]:
print(len(frase))
print(len(saudacao))

17
9


In [40]:
frase = frase.replace('a todos','galerinha!')
print(frase)
saudacao = saudacao.replace('tarde','noite')
print(saudacao)

Boa tarde galerinha!
Boa noite


In [41]:
frase = [i for i in frase]
print(frase)

['B', 'o', 'a', ' ', 't', 'a', 'r', 'd', 'e', ' ', 'g', 'a', 'l', 'e', 'r', 'i', 'n', 'h', 'a', '!']


In [42]:
for x in frase:
 print(x)

B
o
a
 
t
a
r
d
e
 
g
a
l
e
r
i
n
h
a
!


## Exercício
> Crie um codigo para seguinte frase : "Sabia que o sabiá sabia assubiar" reparticionando por espaços, após isso crie um print format para visualizar cada palavra em uma coluna separada.

In [43]:
sabia = "Sabia que o sabiá sabia assubiar"
sabia = [i for i in sabia]
print(sabia)

['S', 'a', 'b', 'i', 'a', ' ', 'q', 'u', 'e', ' ', 'o', ' ', 's', 'a', 'b', 'i', 'á', ' ', 's', 'a', 'b', 'i', 'a', ' ', 'a', 's', 's', 'u', 'b', 'i', 'a', 'r']


In [44]:
sabia = "Sabia que o sabiá sabia assubiar"
palavras = sabia.split()
print(palavras)
for i in range(8):
 print(i)

['Sabia', 'que', 'o', 'sabiá', 'sabia', 'assubiar']
0
1
2
3
4
5
6
7


In [45]:
for i in range(max([len(x) for x in palavras])):
 print(' '.join(y[i] if i< len(y) else ' ' for y in palavras))

S q o s s a
a u   a a s
b e   b b s
i     i i u
a     á a b
          i
          a
          r


# Introdução a Numpy

> Numpy é uma blibioteca python para desenvolvimento de matrizes. tem por objetivos facilitar na criação de algoritmos matemátcos para selecionar paginas avançadas em relação a arrays.

In [46]:
pip install numpy 

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [47]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [48]:
b = np.ones
print(b)

<function ones at 0x000002007E39C0E0>


In [49]:
b = np.array((4,5,6))
print(b)

[4 5 6]


In [50]:
c = np.ones((3,3))
print(c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [51]:
d = np.eye(5)
print(d)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [52]:
d.max()

np.float64(1.0)

In [53]:
print(a.max())
print(b.max())
print(c.max())
print(d.max())

3
6
1.0
1.0


In [54]:
print(a.sum())
print(b.sum())
print(c.sum())
print(d.sum())

6
15
9.0
5.0


> Para calcular média

In [55]:
print(a.mean())
print(b.mean())
print(c.mean())
print(d.mean())

2.0
5.0
1.0
0.2


>Para desvio padrão

In [56]:
print(round(a.std(),2))
print(round(b.std(),2))
print(round(c.std(),2))
print(round(d.std(),2))

0.82
0.82
0.0
0.4


# Exercicio 2

> Crie uma matriz chamada contar com os números de 0 a 9. Ao final crie uma contagem, média e desvio padrão para essa matriz. Para adicionar de 0 a 9 utilize um for e depois atribua à matriz.